version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum install -y nginx

  pre_build:
    commands:
      - echo Preparing build environment...
      - nginx -g 'daemon off;' &  # Run NGINX in the background

  build:
    commands:
      - echo Building application...
      - cp index.html /usr/share/nginx/html/index.html  # Make sure this path is correct

  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - index.html

